### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by 12buntu** [MycroftAI/mycroft-core#1419]
Using Linux (KDE plasma but not using the plasmoid)
I said "hey mycroft" after running dev_setup and start-mycroft with no errors, but it doesnt work, so I tried start-mycroft debug but it just got me this 

```
Traceback (most recent call last):
  File "/home/neon/mycroft-core/mycroft/client/text/main.py", line 40, in <module>
    import mycroft.version
ImportError: No module named mycroft.version
```

**Comment by schrieveslaach** [comment]
I do have the same error when I was trying to update the [AUR package](https://aur.archlinux.org/packages/mycroft-core/) (my fork is [here](https://gitlab.com/schrieveslaach/mycroft-core-aur)).

**Comment by forslund** [comment]
Hi,

this usually happens if the virtualenv doesn't get setup correctly for some reason.

try the following:

```
workon mycroft
python -c "from mycroft.version import CORE_VERSION_STR; print(CORE_VERSION_STR)"
```

If the first line fails the virtualenv hasn't been installed at all (try rerunning the dev_setup script), if the second fails the mycroft-core directory hasn't been added to the virtualenv python path correctly (to try `rm -rf ~/.vritualenvs/mycroft` and then rerun dev_setup).

@12buntu what distro are you running?

**Comment by schrieveslaach** [comment]
I tried them both and none of the commands fails but still not able to start mycroft:

```bash
$ sudo su mycroft-core
$ source /usr/share/mycroft-core/.virtualenvs/mycroft/bin/activate
$ workon mycroft
$ python -c "from mycroft.version import CORE_VERSION_STR; print(CORE_VERSION_STR)"
0.9.16
$ /usr/share/mycroft-core/start-mycroft.sh cli
Initializing...
Starting cli


Traceback (most recent call last):
  File "/usr/share/mycroft-core/mycroft/client/text/main.py", line 40, in <module>
    import mycroft.version
ImportError: No module named mycroft.version
(mycroft)
$ 
```

**Comment by forslund** [comment]
@schrieveslaach Where do you install mycroft. `start-mycroft.sh` is mainly for running a github clone install. Are you keeping that format intact or are you installing into /usr/lib/python2.7/site-packages?

**Comment by schrieveslaach** [comment]
The install downloads the version 0.9.16 from github and extracts the content which will be copied to `/usr/share/mycroft-core`. Then following script will be executed

```bash
chown -R mycroft-core:mycroft-core /usr/share/mycroft-core

touch /usr/share/mycroft-core/.bashrc
echo "# Virtualenv initialization" >> /usr/share/mycroft-core/.bashrc
echo "export WORKON_HOME=\$HOME/.virtualenvs" >> /usr/share/mycroft-core/.bashrc
echo "export PROJECT_HOME=\$HOME/Devel" >> /usr/share/mycroft-core/.bashrc
echo "source /usr/bin/virtualenvwrapper.sh" >> /usr/share/mycroft-core/.bashrc

sudo -Hu mycroft-core bash -c 'source ~/.bashrc' &> /dev/null # Initialize virtualenv

sudo -Hu mycroft-core bash -c 'source ~/.bashrc && mkvirtualenv mycroft --system-site-packages -p $(which python2)'
sudo -Hu mycroft-core bash -c 'source ~/.bashrc && workon mycroft && pip install -r /usr/share/mycroft-core/requirements.txt'
```

The home of `mycroft-core` is `/usr/share/mycroft-core`.

**Comment by forslund** [comment]
@schrieveslaach Looks like it doesn't find the virtualenv. Maybe you can try to run it with

`bash -x /usr/share/mycroft-core/start-mycroft.sh cli`

To get some more debugging info. I do however think your case is rather special since it's a system install.

I also see that the virtualenv is setup in the user mycroft-core. Maybe that is causing issues since start-mycroft.sh uses the current user?

**Comment by schrieveslaach** [comment]
Before I start Mycroft I make sure that the `mycroft-core` will be used, e. g. `sudo su mycroft-core`. 

Here is the debug output:

```bash
$ bash -x /usr/share/mycroft-core/start-mycroft.sh cli
+ SOURCE=/usr/share/mycroft-core/start-mycroft.sh
+ script=/usr/share/mycroft-core/start-mycroft.sh
+ script=start-mycroft.sh
+++ dirname /usr/share/mycroft-core/start-mycroft.sh
++ cd -P /usr/share/mycroft-core
++ pwd
+ DIR=/usr/share/mycroft-core
+ scripts_dir=/usr/share/mycroft-core/scripts
+ mkdir -p /usr/share/mycroft-core/scripts/logs
+ '[' -z /usr/share/mycroft-core/.virtualenvs ']'
+ VIRTUALENV_ROOT=/usr/share/mycroft-core/.virtualenvs/mycroft
+ _script=
+ first_time=true
+ _opt=cli
+ shift
+ _params=
+ case ${_opt} in
+ launch-process cli
+ true
+ echo Initializing...
Initializing...
+ /usr/share/mycroft-core/scripts/prepare-msm.sh
+ source /usr/share/mycroft-core/.virtualenvs/mycroft/bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /usr/bin/bash ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/usr/share/mycroft-core/.virtualenvs/mycroft
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/usr/share/mycroft-core/.virtualenvs/mycroft/bin:/home/marc/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/staruml/:/home/marc/.gem/ruby/2.5.0/bin
++ PATH=/usr/share/mycroft-core/.virtualenvs/mycroft/bin:/usr/share/mycroft-core/.virtualenvs/mycroft/bin:/home/marc/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/staruml/:/home/marc/.gem/ruby/2.5.0/bin
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /usr/share/mycroft-core/.virtualenvs/mycroft
++ PS1='(mycroft) '
++ export PS1
++ alias pydoc
++ '[' -n /usr/bin/bash ']'
++ hash -r
+ first_time=false
+ name-to-script-path cli
+ case ${1} in
+ _script=/usr/share/mycroft-core/mycroft/client/text/main.py
+ echo 'Starting cli'
Starting cli
+ python /usr/share/mycroft-core/mycroft/client/text/main.py


Traceback (most recent call last):
  File "/usr/share/mycroft-core/mycroft/client/text/main.py", line 40, in <module>
    import mycroft.version
ImportError: No module named mycroft.version
```

**Comment by forslund** [comment]
@schrieveslaach I just realized that since you're not running the complete dev_setup script you're not getting the python path updated. See https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L163

**Comment by schrieveslaach** [comment]
@forslund, I tried to add the variable and create the file, but still no luck. Here is the new script:

```bash
touch /usr/share/mycroft-core/.bashrc
echo "# Virtualenv initialization" >> /usr/share/mycroft-core/.bashrc
echo "export WORKON_HOME=\$HOME/.virtualenvs" >> /usr/share/mycroft-core/.bashrc
echo "export VENV_PATH_FILE=\$HOME/.virtualenvs/mycroft/lib/python2.7/site-packages/_virtualenv_path_extensions.pth" >> /usr/share/mycroft-core/.bashrc
echo "export PROJECT_HOME=\$HOME/Devel" >> /usr/share/mycroft-core/.bashrc
echo "source /usr/bin/virtualenvwrapper.sh" >> /usr/share/mycroft-core/.bashrc

sudo -Hu mycroft-core bash -c 'source ~/.bashrc' &> /dev/null # Initialize virtualenv

sudo -Hu mycroft-core bash -c 'source ~/.bashrc && mkvirtualenv mycroft --system-site-packages -p $(which python2)'
sudo -Hu mycroft-core bash -c 'source ~/.bashrc && echo "import sys; sys.__plen = len(sys.path)" > "$VENV_PATH_FILE" || return 1'
sudo -Hu mycroft-core bash -c "source ~/.bashrc && echo \"import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)\" >> \"\$VENV_PATH_FILE\" || return 1"
sudo -Hu mycroft-core bash -c 'source ~/.bashrc && workon mycroft && pip install -r /usr/share/mycroft-core/requirements.txt'
```

**Comment by forslund** [comment]
Hmm, can it be that you use `--system-site-packages` while the update to python path is set in the virtualenv site-packages directory.

You can also try to update the PYTHONPATH for the mycroft-core user to include the mycroft-core directory, which should work just as well

**Comment by forslund** [comment]
Looking again you'd need all the code linked above down to line 174. The code actually adding mycroft-core to the virtualenv path starts at https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L169

**Comment by schrieveslaach** [comment]
@forslund, is it correct that when someone starts the bus service, mycroft tries to call `chmod` on `/usr/share/mycroft-core/scripts/../msm/msm`?

**Comment by forslund** [comment]
@schrieveslaach Yes, it calls https://github.com/MycroftAI/mycroft-core/blob/dev/scripts/prepare-msm.sh to make sure it can be invoked.

But we're really hijacking @12buntu's issue here. Please create a separate issue if you have more problems.

**Comment by femans** [comment]
Has this been solved? I can't follow the thread. But I have the same issue, with a git install of dev_setup.sh on an arch linux system, which I had to hack due to another issue with pygtk.

**Comment by femans** [comment]
I think i fixed/hacked this by typing: `add2virtualenv .` from the mycroft-core directory

**Comment by cowang4** [comment]
I had this error message because I didn't clone into a folder named mycroft-core, so the install script didn't add the python module with that name into the virtualenv. I'll submit a pr with a fix.

**Comment by forslund** [comment]
@cowang4 do you think this issue can be considered resolved now?

**Comment by cowang4** [comment]
It seems to me that there are multiple bugs discussed in this issue thread. My PR only fixed one of them which was if the mycroft-core folder was named something else. But, it seems like almost everyone else's bugs have been fixed, except for the OP @12buntu. Can anyone still reproduce this bug using the `dev_setup.sh` script?

**Comment by MatthewScholefield** [comment]
We've recently made a lot of changes to the virtualenv with the move to Python 3 and the msm changes. Since there's been no response in 30 days I'm closing this issue. If anyone still has a problem feel free to reopen this.
